### ISSUE TITLE
Non-Normative Guidance in Using NIEM with JSON

### ISSUE THREAD

**Issue by jlainc** [NIEM/NIEM.github.io#9] opened 2016-08-04 21:09 UTC
I fail to understand the need for the level of complexity which appears to be in the current document. Why are we treating the simple task of finding a way to allow JSON developers to do NIEM exchanges with JSON as if we must construct a JSON interface which contains all of the NIEM compliance constructs found in NIEM XML? It is not as if the JSON developers are going to actually want to know this information.  If that were the case, then they would have learned how to do it in XML.  The cold hard fact is that the reason why JSON developers want us to allow them to submit with JSON is EXACTLY because they do NOT want to have to learn all of the NIEM constructs and rules.  As such, we should simply give them a JSON Schema and sample JSON document, and then let them do their job!

I already have a working example of how this can be done in which we used the Nibrs IEPD 4.0 exchange. RIGHT NOW we have a fully functional exchange which can take an XML or a JSON document and import it into the exact same SQL database.  I have included 3 files below which we use in our process:

This is a Nibrs XML document:
[nibrs.xml.txt](https://github.com/NIEM/NIEM.github.io/files/402711/nibrs.xml.txt)
This is a JSON Schema definition which matches our Nibrs exchange:
[Json Schema.txt](https://github.com/NIEM/NIEM.github.io/files/402712/Json.Schema.txt)
This is an actual JSON exchange document:
[Json File.json.txt](https://github.com/NIEM/NIEM.github.io/files/402713/Json.File.json.txt)

I see no reason to go to the lengths in which this document outlines in order to accomplish the mission at hand. We will simply be wasting a ton of time, energy, and money for something that they JSON community WILL NOT care about in the end.  All they want is a way to keep them from having to learn XML and NIEM...

**Comment by webb** [comment] 2016-08-05 16:51
I definitely understand why you might be frustrated with a NIEM JSON approach, when what you want is a plain JSON approach. This guidance is for JSON developers who are seeking a NIEM-conformant information exchange in JSON. To be NIEM-conformant, it has to meet criteria that you probably don't care about, for example:

1. Have its meaning defined by a NIEM IEPD: the NIEM types, relationships as defined by NIEM elements
1. Be consistent across implementations: different instances of an IEPD should be represented the same way.
1. Have names grounded to namespace-qualified names in the NIEM IEPD. We have to distinguish between different versions of a namespace, as well as between the same local name defined by completely different namespaces. 
1. Respect the modeling constructs in NIEM: what does an "augmentation" mean vs. a regular element, versus an element with structures:ref, etc.

If you want to express NIEM-defined data using JSON between components, that's fine; the exchanged data just won't be NIEM-conformant.

This approach uses JSON-LD, a JSON vocabulary for linked data, which helps maintain the criteria above. It has a context function (`@context`) that can simplify JSON instances, and can be reused across multiple instances. Are you familiar with JSON-LD? I'd like to provide an LD example of the instance you provided. Is there any chance you can send me that IEPD? It would help.

I tried to run what you posted through the online JSON Schema validator at https://json-schema-validator.herokuapp.com, but it would not validate. ("Validation results: failure"). Should that work?

When I look at what you sent, I see lots of things in the instance and schema that don't seem to be from the instance document, e.g.:
* key "Submissions" : the XML just has "Submission"
* key "SubmissionGuid" : not in the XML, with value not in the XML
* `"ObjectAugmentationPoint": null` : why say this if it's not in the XML? Does your method make you explicitly null out every non-populated field?
* `"ObjectType" : "NIBRS_Model.Model.NIBRS_Source.dbo.ReportDate"` : this seems to have no relationship to the XML

How were the JSON instance and schema file generated? It looks like there are lots of things in both that don't relate to the XML instance, nor to the IEPD.

Anyway, I'd like to work with you through this, and see if the dialog can help improve our approach.

Thanks,
Webb

**Comment by jlainc** [comment] 2016-08-05 18:00
Hi Webb,

Thanks for your reply to my comments regarding the NIEM with JSON document. You stated in your email, "To be NIEM-conformant, it has to meet criteria that you probably don't care about". However, you should know that I have been involved with the NIEM process dating all the way back to 2003 with the very beginnings of GJXDM, when I was the representative for the Alabama Courts system assigned to the GTRI project. I am now a sitting IJIS I-TAC member, so I am fully aware of how NIEM works, and what the intentions are for the XML exchange complexity. Where I think the current process as outlined by the "Non-conformant" document is missing the mark is with the notion that there are, "JSON developers who are seeking a NIEM-conformant information exchange in JSON". Based on my experience with the JSON community, I really don't think they care about the "NIEM-conformant" structure of the JSON exchange.  They just want to be able to create a valid NIEM submission WITHOUT needing to know anything about NIEM-conformance. Otherwise, if they really cared that much about "NIEM-conformance", then they would already be doing the exchanges in XML. I fully believe all they are really looking for is a shortcut to allow them to create submissions with JSON...

The NIBRS example that we have constructed is built based on our patent pending NADA (NIEM Automated Database Architecture)/XEDA (XML Exchange Database Automation) technologies, which relies on our other patent-pending ADOM (Automated Database Object Model) technology.  You can watch a quick demo video and learn more at the link below:

http://intelligencedesigns.com/IntelligenceDesigns/blog/Posts/nada.html

In a nutshell, our process ingests an IEPD's schema definitions into SQL Server, and then constructs a relational database model which mirrors the exchange document. Each table in the data structure has a GUID as its primary key (this is required to be able to maintain the relationships across multiple submissions from multiple different entities), which is why in the sample JSON document you see fields like "SubmissionGuid" (Note: The GUIDs are not required for the XML exchanges in our system). Then we apply our ADOM technology to the relational data structure in order to generate a working XML model via auto-generated stored procedures, triggers, views and functions. This allows us to ingest an entire XML exchange document via a single auto-generated stored procedure, as well as extract an entire XML exchange document from a single stored procedure.

We use the ADOM technology every day in all of our development projects. It is basically a replacement for the Entity Framework, that is infinitely more performant, and much simpler to manage. We have a component of the ADOM framework which constructs a C# class library in the middle tier that can directly ingest the ADOM XML output, and then serialize that out as a JSON object.  All of our development projects us JSON objects on the client side. This is why we were able to create a JSON exchange for a NIEM IEPD definition so quickly.

By default the ADOM model uses plurality of objects to allow for a clean definition of 1-to-8 relationships in the middle tier, however, this is an option for the NIEM exchanges which can be removed if desired. I just left it in the default behavior for the initial solution. The plurality you noted on the "Submissions" element, means that you could technically process multiple Nibrs Submission documents in the same exchange transport operation. The JSON schema and document instance was generated via the NewtonSoft tools for JSON. You can learn about this tool here:

http://www.newtonsoft.com/json

What we did was to generate a "blank" JSON document with all "NULL" values, in order to give the user a fully completed JSON document structure. This way there is no question for the developer on how the JSON document should be structured. They can simply populate the fields for which they have values, and then submit the document. All elements with NULL values are simply ignored during the processing. This is the SIMPLEST approach to solving the "NIEM with JSON" issue. The developer needs not care about understanding the NIEM schema definition.  They can simply populate the document and be done...

So, the Nibrs exchange was built on the IEPD, and therefore is a NIEM-compliant exchange in the grand sense. It can take a NIEM-compliant XML document built for the Nibrs exchange and process it into our data structure. Since the JSON portion of the exchange was constructed based on the NIEM-compliant schema definitions via the same relational data structure, it too is designed to transport NIEM data to and from the same data structure that the XML exchange uses. Therefore, it IS a NIEM-compliant exchange in that sense.

I would be happy to setup a WebEx meeting to show you first hand what I am talking about if you so desire?  Just let me know...

Sincerely,
Larry Arrington
334-233-0561

**Comment by pamam** [comment] 2016-08-09 19:40
I agree with you Larry.  The job of a web service is to communicate not to ingest, digest and then regurgitate so that the receiving end has to do a lot of extra work sorting out the response

**Comment by webb** [comment] 2016-08-09 22:04
@jlainc wrote:
> Based on my experience with the JSON community, I really don't think they care about the "NIEM-conformant" structure of the JSON exchange. They just want to be able to create a valid NIEM submission WITHOUT needing to know anything about NIEM-conformance. 

Yeah, there's a catch-22 in there: if people don't care about NIEM, how do they know what a "valid NIEM submission" is? Someone who understands the IEPD needs to define a JSON syntax for the JSON senders and receivers. I think there are a couple of options:

1. You don't want to worry about NIEM-conformant JSON. For example, you've got a database & the database speaks JSON (call it *database-JSON*), and that's good enough. Then you can have people submit database-JSON, and you don't worry about NIEM anything. They just have to speak *database*, and other software that uses the database can interact with NIEM XML exchanges.

1. You want the JSON to be NIEM-conformant, in that **anyone** who understands the IEPD will understand the JSON. That's what this guidance is trying to hit. 

So, in either case, presuming you've got non-NIEM JSON developers on the outside, somebody has to define what the exchange format is. You created your format based on what your automagic software stack reads & writes. I might instead define a format using the NIEM guidance. Either way, someone defines the exchange format & the JSON guys read and write that. 

Honestly, I don't think that the JSON generated by the guidance is all that complicated. Here's my first cut, which I generated using the guidance doc. I ran the XML instance you posted ([nibrs.xml.txt](https://github.com/NIEM/NIEM.github.io/files/402711/nibrs.xml.txt)) through an XSL v3 transform, generating JSON-LD, which I ran through the compactor at the [JSON-LD Playground](http://json-ld.org/playground/) to simplify the JSON's layout. This yielded [nibrs-xml-as-json-ld-compacted.json.txt](https://github.com/NIEM/NIEM.github.io/files/409936/nibrs-xml-as-json-ld-compacted.json.txt).

If you take a look at it, you might find that it's just not that complicated. It uses JSON-LD, a W3C recommendation, to handle namespaces and resolving IDs and references, but you could easily give a developer this JSON and say "make it look like that", and they shouldn't have too much trouble.

BTW, the stuff under the "@context" key can (and should) be offloaded into a separate resource and referenced, so that it doesn't have to be sent back and forth in runtime exchanges. There are tricks you can use in @context to simplify the JSON data further. For example, you can coin the QNames as simple names, so you don't have names with colons in the JSON. As well, the way IDs and References work can be refined a bit to simplify the instances.

I'm anxious to hear your thoughts on this. Thanks for your input.

Webb

**Comment by jlainc** [comment] 2016-08-10 16:18
Hi Webb,

When I said the following: "_Based on my experience with the JSON community, I really don't think they care about the "NIEM-conformant" structure of the JSON exchange. They just want to be able to create a valid NIEM submission WITHOUT needing to know anything about NIEM-conformance_."

What I meant to convey (I apologize for the lack of clarity...) is that the JSON development community at large does not really care about understanding the intricacies about how to construct a NIEM-conformant exchange document instance. All they want to know is the end resulting structure, and they don't really care about how or why that structure was derived. Therefore, it was our approach to simply give them exactly that: An exchange document in JSON which WILL translate to a NIEM-conformant data structure. 

@webb - "_2. You want the JSON to be NIEM-conformant, in that anyone who understands the IEPD will understand the JSON. That's what this guidance is trying to hit._"

My contention is that most developers who are actually building the exchange DO NOT want to have to fully understand the IEPD. That is why I am suggesting that we provide them with a NULL populated instance document, and they can simply fill in the appropriate blanks. If you are expecting the JSON community to actually desire to understand the IEPD and thus be able to derive the resulting JSON structure on their own recognizance, then I believe you will see a lower rate of acceptance than you have on the NIEM-XML front. Just supply a JSON schema and blank JSON instance document as part of the IEPD. Done...

The example files I presented in my first response were simply the "default" structure as generated by our "automagic software", but we could modify our process to accept your JSON-LD instance without too much difficulty.  I am simply asserting that we should provide the instance document as part of the IEPD, and allow the developers to simply populate it. I guarantee the JSON community actually cares less about NIEM than the XML community, and they just want to be able to build the exchange and mark off that task. 

This is actually the entire reason why we built the NADA tool for the XML community in the first place! The nightmarish experience we had constructing the first VN SSP exchange of its kind in the US with the selected partner vendor told me that we had to come up with a simpler way to implement NIEM exchanges once the IEPD has been defined. Our tool does that, and requires virtually no .net development on the part of the senders or recipient. This should cut the cost of implementing NIEM exchanges by at least 50%, and drastically decrease the time it takes to implement.

There are other approaches which I have recommended (see attached document) to simplify the JSON document structure even further, and thus give us an even greater level of acceptance within the JSON community. I really think we need to take the opportunity to focus this NIEM-JSON project more on gaining acceptance and thus increasing the NIEM footprint nation wide.
[How to Handle JSON in NIEM.docx](https://github.com/NIEM/NIEM.github.io/files/411580/How.to.Handle.JSON.in.NIEM.docx)

I am just begging you guys to please not take this NIEM-JSON project down a similar path as the NIEM-XML adventure, and end up with a model which is so complex that no JSON developer will want to use it. We are already having a difficult enough time getting NIEM-XML acceptance nation-wide. I believe that if done correctly, this NIEM-JSON project could garner more support from the development community, and thus a greater level of acceptance and adoption across the board.

Sincerely,
Larry Arrington
334-233-0561

**Comment by pamam** [comment] 2016-08-10 20:26
Larry,
 
I'm with you.  I just got into WCF Services and don't have time to learn all this NIEM stuff.  I downloaded a bunch of files from the site and was completely overwhelmed.  The job of these institutions is to simplify things not to create a complete new and complex infrastructure around a very simple Microsoft API which is easy to develop with.  JSON also was designed to make things simple, however it seams NIEM is determined to make it complex.
 
Count me out.
 
Thanks,
 
Mel
 
-----Original Message-----

**Comment by webb** [comment] 2016-08-10 21:45
So, looking at your sample JSON instance, it looks a whole lot like the NIEM conformant JSON for the same message. The few changes I see:

1. The NIEM JSON uses @context to define prefixes, instead of using xmlns:*. The @context is defined by JSON-LD, and it allows lots of flexibility in the JSON data.

1. The NIEM JSON uses "@id" instead of structures:id and structures:ref. Again, JSON-LD defines that.

1. The NIEM JSON doesn't flatten the data structures from the IEPD.

Anything else different? Are these changes such a big lift from your syntax?

I agree with you that most JSON people won't care about NIEM-conformant JSON. But in both scenarios you have someone who understands the IEPD defining a JSON format for those who don't, and the difference between the two syntaxes seems to be pretty small. 

However, for the change in syntax we get fidelity to the IEPD, support of linked data methodology and JSON-LD methods and tools, an RDF representation, and scaling of data across many IEPDs and vocabularies.

What would you have us change in our approach?

**Comment by jlainc** [comment] 2016-08-11 15:32
Hi Webb,

We can obviously modify our "automagic software" process to use just about any JSON syntax chosen. What I am advocating for is to take the simplest route possible (from the end-user's perspective) with the NIEM-JSON implementation. Quite frankly, I do not understand why we are not significantly farther along in the process than we find ourselves to date? This is a large part of my frustrations with this topic. I was first asked by the I-TAC committee to provide the suggestions I documented in the previous attachments all the way back in September of 2015. Here we are almost a full year later, and you guys have not even begun discussing those types of measures yet? We seem to still be stuck in the mud of redefining NIEM within the context of JSON.

While I agree that ANYTHING dealing with NIEM is going to be complex by its very nature based on the overarching complexity of the model, I believe the NIEM-JSON solution could and should be a simple one. Give the JSON development community a simplified structure, the JSON schema and a fully-formed JSON instance document with NULL values as part of the IEPD, and then just allow the developers to populate and submit the document. **PLEASE** don't spend another year pontificating over the intricacies between XML and JSON...  We have had a WORKING solution to allow NIEM-JSON exchanges for almost a year now.  This is not rocket science...

Sincerely,
Larry Arrington
334-233-0561

**Comment by jlainc** [comment] 2016-08-25 21:23
Hi Webb,
I have been working with our NADA toolset in an attempt to remove all “pluralized” nodes. However, I am running into an issue on which I would like your input. XML allows for multiple nodes within the same level of a document to have the same name (i.e. – duplicates). In the NIBRS exchange instance referenced earlier, there is an example of this with regards to the nc:Person records as seen in the excerpt below:
<nibrs:Report>
     <nibrs:ReportHeader>
     <nc:Incident>
     <j:Offense s:id="Offense1">
     <nc:Item>
     <nc:Substance>
     <nc:Person s:id="PersonVictim1">
     <nc:Person s:id="PersonVictim2">
     <nc:Person s:id="PersonSubject1">
     <nc:Person s:id="PersonArrestee1">
     <j:EnforcementOfficial><nc:RoleOfPerson s:ref="PersonVictim1"/> 
     <j:Victim> 
     <j:Victim> 
     <j:Subject> 
     <j:Arrestee s:id="Arrestee1"> 

Notice in the sample above that there are 4 “Person” nodes, and 2 “Victim” nodes at the same level in the document.  The issue is that if you simply transfer this same convention “as-is” to JSON, it causes problems. While the JSON Data Interchange Format (ECMA-404) doesn’t say anything about duplicate names (keys) within a JSON document, The JavaScript Object Notation (JSON) Data Interchange Format (RFC7159) says that the names within an object SHOULD be unique. Here is an extract from that document:

“_An object whose names are all unique is interoperable in the sense that all software implementations receiving that object will agree on the name-value mappings. When the names within an object are not unique, the behavior of software that receives such an object is unpredictable. Many implementations report the last name/value pair only. Other implementations report an error or fail to parse the object, and some implementations report all of the name/value pairs, including duplicates._”

We have observed this issue with multiple JSON parsing processors. Thus, in order to maintain the naming conventions of the XML schema definition for the NIBRS exchange, then it would be necessary to wrap the duplicates in a unique node which would identify them as a “collection” within the object. This is the reason why we chose to insert the concept of plurality within our original ADOM framework. It makes a clear and present distinction between “collections” and other “elements” within the document. This translates neatly into a well-defined class structure allowing us to deserialize the XML and/or JSON directly into our class with the standard deserializers, without any custom hacking required.

Thus, in this instance it may be necessary to use plural nodes (or some other wrapper) which are NOT part of the NIEM exchange definition within the JSON document instance. 

Do you have any thoughts on this?

Sincerely,
Larry Arrington
334-233-0561

**Comment by jlainc** [comment] 2016-08-25 21:30
<nibrs:Report>
   <nibrs:ReportHeader>
   <nc:Incident>
   <j:Offense s:id="Offense1">
   <nc:Item>
   <nc:Substance>
   <nc:Person s:id="PersonVictim1">
   <nc:Person s:id="PersonVictim2">
   <nc:Person s:id="PersonSubject1">
   <nc:Person s:id="PersonArrestee1">
   <j:EnforcementOfficial><nc:RoleOfPerson s:ref="PersonVictim1"/> 
   <j:Victim> 
   <j:Victim> 
   <j:Subject> 
   <j:Arrestee s:id="Arrestee1">

**Comment by jlainc** [comment] 2016-08-25 21:32
Sorry, but the xml tags are obviously causing issues with the html on the comments. So I am just including the entire xml file referenced above.
[nibrs.xml.txt](https://github.com/NIEM/NIEM.github.io/files/438106/nibrs.xml.txt)

**Comment by webb** [comment] 2017-06-27 15:28
We're relying on JSON-LD to handle properties that occur more than once. So this would look something like the following (leaving stuff out, but trying to include enough to show how it's done.

BTW, we're also looking at providing a default JSON-LD context; a draft is at https://github.com/webb/NIEM-Releases/blob/dev-json-ld-context/niem/context/niem-4.0.jsonld

Does this make sense? I'm going to close this issue, but please open a new one for any observations.

```json
{
    "nc:Incident": {
        "nc:ActivityIdentification": {
            "nc:IdentificationID": "54236732"
        },
        "nc:Person": [
            {
                "@id": "#PersonVictim1",
                "nc:PersonAgeMeasure": {
                    "nc:MeasureIntegerValue": 32,
                },
                "j:PersonEthnicityCode": "N",
            }, {
                "@id": "#PersonVictim2",
                "j:PersonEthnicityCode": "U",
                "nc:PersonInjury": {
                    "j:InjuryCategoryCode": "N"
                }
            }, {
                "@id": "#PersonSubject1",
                "nc:PersonAgeMeasure": {
                    "nc:MeasureIntegerRange": {
                        "nc:RangeMaximumIntegerValue": 30,
                        "nc:RangeMinimumIntegerValue": 25
                    }
                },
                "j:PersonEthnicityCode": "N"
            }
        ],
        "j:EnforcementOfficial": {
            "nc:RoleOfPerson": {
                "@id": "#PersonVictim1"
            }
        }
    }
}
```

**Closed by webb** 2017-06-27 15:28 UTC
